<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="DESKTOP-5HBRUB1" failures="5" tests="7" name="Test(failed)(failed)" time="0.184" errors="0" timestamp="2021-03-31T20:34:23 IST">
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases1" name="sample2" time="0.011"/>
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases1" name="sample4" time="0.008"/>
  <testcase classname="ToRun_FailTestCases.ToRun_FailTestCases3" name="sample24" time="0.007">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ToRun_FailTestCases.ToRun_FailTestCases3.sample24(ToRun_FailTestCases3.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sample24 -->
  <testcase classname="ToRun_FailTestCases.ToRun_FailTestCases3" name="sample22" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ToRun_FailTestCases.ToRun_FailTestCases3.sample22(ToRun_FailTestCases3.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sample22 -->
  <testcase classname="ToRun_FailTestCases.ToRun_FailTestCases3" name="sample23" time="0.004">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ToRun_FailTestCases.ToRun_FailTestCases3.sample23(ToRun_FailTestCases3.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sample23 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases2" name="sample31" time="0.006">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ToRun_FailTestCases.RunOnlyFailTestCases2.sample31(RunOnlyFailTestCases2.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sample31 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases2" name="sample33" time="0.004">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ToRun_FailTestCases.RunOnlyFailTestCases2.sample33(RunOnlyFailTestCases2.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sample33 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases1" name="sample3" time="0.0">
    <ignored/>
  </testcase> <!-- sample3 -->
  <testcase classname="ToRun_FailTestCases.ToRun_FailTestCases3" name="sample20" time="0.0">
    <ignored/>
  </testcase> <!-- sample20 -->
  <testcase classname="ToRun_FailTestCases.ToRun_FailTestCases3" name="sample21" time="0.0">
    <ignored/>
  </testcase> <!-- sample21 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases2" name="sample55" time="0.0">
    <ignored/>
  </testcase> <!-- sample55 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases2" name="sample44" time="0.0">
    <ignored/>
  </testcase> <!-- sample44 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases1" name="sample5" time="0.0">
    <ignored/>
  </testcase> <!-- sample5 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases2" name="sample32" time="0.0">
    <ignored/>
  </testcase> <!-- sample32 -->
  <testcase classname="ToRun_FailTestCases.RunOnlyFailTestCases1" name="sample1" time="0.0">
    <ignored/>
  </testcase> <!-- sample1 -->
</testsuite> <!-- Test(failed)(failed) -->
